# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/snake.xdc

# Block Designs: bd/snake/snake.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake || ORIG_REF_NAME==snake} -quiet] -quiet

# IP: bd/snake/ip/snake_processing_system7_0_0/snake_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_processing_system7_0_0 || ORIG_REF_NAME==snake_processing_system7_0_0} -quiet] -quiet

# IP: bd/snake/ip/snake_rgb2dvi_0_0/snake_rgb2dvi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_rgb2dvi_0_0 || ORIG_REF_NAME==snake_rgb2dvi_0_0} -quiet] -quiet

# IP: bd/snake/ip/snake_clk_wiz_0_0/snake_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_clk_wiz_0_0 || ORIG_REF_NAME==snake_clk_wiz_0_0} -quiet] -quiet

# IP: bd/snake/ip/snake_display_timing_0_0/snake_display_timing_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_display_timing_0_0 || ORIG_REF_NAME==snake_display_timing_0_0} -quiet] -quiet

# IP: bd/snake/ip/snake_SNES_0_0/snake_SNES_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_SNES_0_0 || ORIG_REF_NAME==snake_SNES_0_0} -quiet] -quiet

# IP: bd/snake/ip/snake_showOnLED_0_0/snake_showOnLED_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_showOnLED_0_0 || ORIG_REF_NAME==snake_showOnLED_0_0} -quiet] -quiet

# IP: bd/snake/ip/snake_buttons_0_0/snake_buttons_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_buttons_0_0 || ORIG_REF_NAME==snake_buttons_0_0} -quiet] -quiet

# IP: bd/snake/ip/snake_snakeController_0_1/snake_snakeController_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_snakeController_0_1 || ORIG_REF_NAME==snake_snakeController_0_1} -quiet] -quiet

# XDC: bd/snake/snake_ooc.xdc
